# Generated by Django 2.0.7 on 2018-07-28 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fuffilled', models.BooleanField(default=False)),
                ('acceptedTutors', models.ManyToManyField(blank=True, default=None, related_name='acceptedTutors', to='main.AppUser')),
                ('avaliableTutors', models.ManyToManyField(blank=True, related_name='avaliableTutors', to='main.AppUser')),
                ('chosenTutor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chosenTutor', to='main.AppUser')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='request',
            name='requestedSubject',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='requestedSubject', to='main.Subject'),
        ),
        migrations.AddField(
            model_name='request',
            name='tutee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutee', to='main.AppUser'),
        ),
        migrations.AddField(
            model_name='appuser',
            name='subjectsOffered',
            field=models.ManyToManyField(related_name='subjectsOffered', to='main.Subject'),
        ),
    ]
