# Generated by Django 2.0.7 on 2018-07-28 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='email',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='appuser',
            name='timezone',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
