# Generated by Django 2.0.7 on 2018-07-28 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20180728_1446'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acceptedTutors', models.ManyToManyField(related_name='acceptedTutors', to='main.AppUser')),
                ('avaliableTutors', models.ManyToManyField(related_name='avaliableTutors', to='main.AppUser')),
                ('chosenTutor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='chosenTutor', to='main.AppUser')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('MAT', 'Mathematics'), ('GEO', 'Geography'), ('ENG', 'English'), ('MAN', 'Mandarin')], max_length=3)),
            ],
        ),
        migrations.DeleteModel(
            name='App_User',
        ),
        migrations.AddField(
            model_name='request',
            name='requestedSubject',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='requestedSubject', to='main.Subject'),
        ),
        migrations.AddField(
            model_name='request',
            name='tutee',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tutee', to='main.AppUser'),
        ),
        migrations.AddField(
            model_name='appuser',
            name='subjectsOffered',
            field=models.ManyToManyField(to='main.Subject'),
        ),
    ]
