# Generated by Django 2.0.7 on 2018-07-28 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20180728_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='acceptedTutors',
            field=models.ManyToManyField(null=True, related_name='acceptedTutors', to='main.AppUser'),
        ),
        migrations.AlterField(
            model_name='request',
            name='avaliableTutors',
            field=models.ManyToManyField(null=True, related_name='avaliableTutors', to='main.AppUser'),
        ),
        migrations.AlterField(
            model_name='request',
            name='chosenTutor',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chosenTutor', to='main.AppUser'),
        ),
    ]
