# Generated by Django 2.0.7 on 2018-07-28 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20180728_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='acceptedTutors',
            field=models.ManyToManyField(default=None, null=True, related_name='acceptedTutors', to='main.AppUser'),
        ),
    ]
