# Generated by Django 2.0.7 on 2018-07-28 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20180728_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='acceptedTutors',
            field=models.ManyToManyField(blank=True, default=None, related_name='acceptedTutors', to='main.AppUser'),
        ),
        migrations.AlterField(
            model_name='request',
            name='avaliableTutors',
            field=models.ManyToManyField(blank=True, related_name='avaliableTutors', to='main.AppUser'),
        ),
        migrations.AlterField(
            model_name='request',
            name='chosenTutor',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chosenTutor', to='main.AppUser'),
        ),
    ]
