# Generated by Django 2.0.7 on 2018-07-28 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20180728_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='subjectsOffered',
            field=models.ManyToManyField(related_name='subjectsOffered', to='main.Subject'),
        ),
    ]
