# Generated by Django 2.0.7 on 2018-07-28 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20180728_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='fuffilled',
            field=models.BooleanField(default=False),
        ),
    ]
